name: Python tests

on: [push]

env:
  PYTHON_VERSION: 3.12
  POETRY_VERSION: 1.7.1
  PROJECT_KEY: yuttasartviratpan_shared-workflow-test
  AZURE_WEBAPP_NAME: your-app-name

jobs:
  get-env:
    name: Get Environment vars
    runs-on: ubuntu-latest
    outputs:
      PYTHON_VERSION: ${{ env.PYTHON_VERSION }}
      POETRY_VERSION: ${{ env.POETRY_VERSION }}
      PROJECT_KEY: ${{ env.PROJECT_KEY }}
    steps:
      - run: echo "null"

  lint:
    needs: get-env
    uses: yuttasartviratpan/shared-workflow-test/.github/workflows/python-lint.yml@main
    with:
      python_version: ${{ needs.get-env.outputs.PYTHON_VERSION }}

  test-and-sonarqube:
    needs: get-env
    uses: yuttasartviratpan/shared-workflow-test/.github/workflows/python-test-sonarqube.yml@main
    with:
      python_version: ${{ needs.get-env.outputs.PYTHON_VERSION }}
      poetry_version: ${{ needs.get-env.outputs.POETRY_VERSION }}
      project_key: ${{ needs.get-env.outputs.PROJECT_KEY }}
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  azure-devops:
    needs:
      - get-env
      - lint
      - test-and-sonarqube
    uses: yuttasartviratpan/shared-workflow-test/.github/workflows/python-deploy.yml@main
    with:
      python_version: ${{ needs.get-env.outputs.PYTHON_VERSION }}
      poetry_version: ${{ needs.get-env.outputs.POETRY_VERSION }}
      project_key: ${{ needs.get-env.outputs.PROJECT_KEY }}
      azure_webapp_name: ${{ needs.get-env.outputs.AZURE_WEBAPP_NAME }}
    secrets:
      AZURE_PUBLISHED_PROFILE: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_121271E473FB4C4FBDB9B3C1BA0DD5A6 }}
