name: Build and deploy Python app to Azure Web App

on:
  workflow_call:
    inputs:
      python_version:
        required: false
        default: "3.11"
        type: string
      poetry_version:
        required: false
        default: "1.6.1"
        type: string
      project_key:
        required: true
        type: string
      azure_webapp_name:
        required: true
        type: string
      extra_registry_name:
        required: false
        default: ""
        type: string

    secrets:
      AZURE_PUBLISHED_PROFILE:
        required: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ inputs.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}

      - name: Install poetry ${{ inputs.poetry_version }}
        run: |
          python -m pip install --upgrade pip
          pip install poetry==${{ inputs.poetry_version }}
          poetry config installer.max-workers 10 --local

      - name: Setup Extra Registry
        if: ${{ inputs.extra_registry_name }}
        run: |
          poetry config --local http-basic.${{ inputs.extra_registry_name }} ${{ secrets.extra_registry_name }} ${{ secrets.extra_registry_password }}

      - name: Install dependencies
        run: |
          poetry install

      - name: Build artifact
        run: |
          poetry build

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            ./dist/*.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app


      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: ${{ inputs.azure_webapp_name }}
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_PUBLISHED_PROFILE }}